# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1c43a24ad7cfc9f591a0890871b066f99541e82892385c3325407f051913e7e194a6834dd3fe4858fb14b94813685c6e3fc34b51836e24e745412b83f57314b

test:
  secret_key_base: 83ff2c20465db62308bf09dd0916daaf087e949eb18002fabea1bf58c81a51a60385b1ece0908115a9cfabe33f7c84a60619f6ed43accd839168e15291b057ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
